language: python
python:
    - "2.7"
before_install:
    - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
    - tar -xzf google-cloud-sdk-155.0.0-linux-x86_64.tar.gz
    - ./google-cloud-sdk/install.sh --quiet
    - pip install -r requirements.txt
    - pip install -r requirements_tests.txt
script:
    - python test_runner.py --test-path tests/ -v --test-pattern test_m*.py ~/google-cloud-sdk