language: python
python:
    - "2.7"
addons:
  apt:
    packages:
    - google-cloud-sdk
    - google-cloud-sdk-app-engine-python
before_install:
    - pip install -r requirements.txt
    - pip install -r requirements_tests.txt
script:
    - py.test