runtime: python27
api_version: 1
threadsafe: yes
automatic_scaling:
  min_pending_latency: 500ms

env_variables:
  BIGQUERY_LOCATION: 'EU'

handlers:
- url: .*
  script: gcp_census.routes.app
  secure: always
  login: admin

libraries:
- name: webapp2
  version: latest
