runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  BIGQUERY_LOCATION: 'EU'

handlers:
- url: .*
  script: main.app
  secure: always
  login: admin

libraries:
- name: webapp2
  version: latest
