cron:
- description: Create BQ tables representing data models
  url: /createModels
  schedule: every day 03:00
  retry_parameters:
    job_retry_limit: 5
    min_backoff_seconds: 2.5
- description: Record metadata about all BigQuery datasets/tables
  url: /bigQuery
  schedule: every day 04:00
